#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "config.h"

void install_gui(void)
{
  printf("Installing dependencies...\n\n");
  system("sudo apt install php-cli php-fpm php-common -y");

  printf("Creating GUI...\n\n");
  system("mkdir /var/www/auto-config");
  
  snprintf(avail_path, sizeof(avail_path), "/etc/nginx/sites-available/auto-config");
  FILE *fp = fopen(avail_path, "w");

  fprintf(fp,
    "server {\n"
    "  listen 3487;\n\n"
    "  server_name _;\n\n"
    "  root /var/www/auto-config;\n"
    "  index index.php index.html index.htm;\n\n"
    "  location / {\n"
    "    autoindex on;\n"
    "    try_files $uri $uri/ =404;\n"
    "  }\n\n"
    "  location ~ \\.php$ {\n"
    "    include snippets/fastcgi-php.conf;\n"
    "    fastcgi_pass unix:/run/php/php-fpm.sock;\n"
    "  }\n"
    "}\n"
  );

  fclose(fp);

  snprintf(enabled_path, sizeof(enabled_path), "/etc/nginx/sites-enabled/auto-config");
  symlink(avail_path, enabled_path);

  if (system("sudo nginx -t") != 0)
  {
    printf("\033[31mUNKNOWN ERROR OCCURRED\033[0m\n");
    printf("GUI failed to install.\n");
    unlink(avail_path);
    unlink(enabled_path);
    system("sudo nginx -t");
    printf("Exiting now...\n\n");
    return;
  }

  char html[STR_LEN];
  snprintf(html, sizeof(html), "/var/www/auto-config/index.html");
  FILE *ht = fopen(html, "w");
  fprintf(ht,
  "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>NGINX Auto Config Generator</title>\n"
        "    <style>\n"
        "        :root {\n"
        "            --bg-color: #0d1117;\n"
        "            --card-bg: #161b22;\n"
        "            --border-color: #30363d;\n"
        "            --text-color: #c9d1d9;\n"
        "            --accent-color: #238636;\n"
        "            --accent-hover: #2ea043;\n"
        "            --code-bg: #010409;\n"
        "        }\n"
        "\n"
        "        body {\n"
        "            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
        "            background-color: var(--bg-color);\n"
        "            color: var(--text-color);\n"
        "            margin: 0;\n"
        "            padding: 20px;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "        }\n"
        "\n"
        "        .container {\n"
        "            width: 100%%;\n"
        "            max-width: 900px;\n"
        "            display: grid;\n"
        "            grid-template-columns: 1fr;\n"
        "            gap: 20px;\n"
        "        }\n"
        "\n"
        "        @media (min-width: 768px) {\n"
        "            .container {\n"
        "                grid-template-columns: 1fr 1fr;\n"
        "            }\n"
        "        }\n"
        "\n"
        "        .card {\n"
        "            background-color: var(--card-bg);\n"
        "            border: 1px solid var(--border-color);\n"
        "            border-radius: 6px;\n"
        "            padding: 20px;\n"
        "        }\n"
        "\n"
        "        h2 {\n"
        "            margin-top: 0;\n"
        "            font-size: 1.25rem;\n"
        "            color: #58a6ff;\n"
        "        }\n"
        "\n"
        "        .form-group {\n"
        "            margin-bottom: 15px;\n"
        "        }\n"
        "\n"
        "        label {\n"
        "            display: block;\n"
        "            margin-bottom: 5px;\n"
        "            font-weight: 600;\n"
        "            font-size: 0.9rem;\n"
        "        }\n"
        "\n"
        "        input[type=\"text\"], select {\n"
        "            width: 100%%;\n"
        "            padding: 8px 12px;\n"
        "            background-color: var(--bg-color);\n"
        "            border: 1px solid var(--border-color);\n"
        "            border-radius: 6px;\n"
        "            color: var(--text-color);\n"
        "            box-sizing: border-box;\n"
        "            font-size: 0.9rem;\n"
        "        }\n"
        "\n"
        "        input[type=\"text\"]:focus, select:focus {\n"
        "            outline: none;\n"
        "            border-color: #58a6ff;\n"
        "        }\n"
        "\n"
        "        pre {\n"
        "            background-color: var(--code-bg);\n"
        "            border: 1px solid var(--border-color);\n"
        "            padding: 15px;\n"
        "            border-radius: 6px;\n"
        "            overflow-x: auto;\n"
        "            font-family: \"SFMono-Regular\", Consolas, \"Liberation Mono\", Menlo, monospace;\n"
        "            font-size: 0.85rem;\n"
        "            line-height: 1.45;\n"
        "            color: #79c0ff;\n"
        "            height: 400px;\n"
        "        }\n"
        "\n"
        "        .btn-apply {\n"
        "            background-color: var(--accent-color);\n"
        "            color: white;\n"
        "            border: none;\n"
        "            padding: 8px 16px;\n"
        "            border-radius: 6px;\n"
        "            cursor: pointer;\n"
        "            font-weight: 600;\n"
        "            width: 100%%;\n"
        "            margin-top: 10px;\n"
        "        }\n"
        "\n"
        "        .btn-apply:hover {\n"
        "            background-color: var(--accent-hover);\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "<div class=\"container\">\n"
        "    <!-- Controls Panel -->\n"
        "    <div class=\"card\">\n"
        "        <h2>NGINX Config Settings</h2>\n"
        "        \n"
        "        <div class=\"form-group\">\n"
        "            <label for=\"preset\">Configuration Mode</label>\n"
        "            <select id=\"preset\" onchange=\"toggleFields()\">\n"
        "                <option value=\"jellyfin\">Preset: Jellyfin Reverse Proxy</option>\n"
        "                <option value=\"nextcloud\">Preset: Nextcloud LEMP Stack</option>\n"
        "                <option value=\"custom_proxy\">Custom: Reverse Proxy</option>\n"
        "                <option value=\"custom_static\">Custom: Static Directory</option>\n"
        "            </select>\n"
        "        </div>\n"
        "\n"
        "        <div class=\"form-group\">\n"
        "            <label for=\"conf_name\">Config File Name</label>\n"
        "            <input type=\"text\" id=\"conf_name\" value=\"jellyfin\" placeholder=\"e.g. my-app\" oninput=\"generateConfig()\">\n"
        "        </div>\n"
        "\n"
        "        <div class=\"form-group\">\n"
        "            <label for=\"domain\">Domain Name</label>\n"
        "            <input type=\"text\" id=\"domain\" value=\"media.example.com\" oninput=\"generateConfig()\">\n"
        "        </div>\n"
        "\n"
        "        <div class=\"form-group\" id=\"port-group\">\n"
        "            <label for=\"port\">Target Port</label>\n"
        "            <input type=\"text\" id=\"port\" value=\"8096\" oninput=\"generateConfig()\">\n"
        "        </div>\n"
        "\n"
        "        <div class=\"form-group\" id=\"path-group\" style=\"display: none;\">\n"
        "            <label for=\"path\">Root Directory Path</label>\n"
        "            <input type=\"text\" id=\"path\" value=\"/var/www/html\" oninput=\"generateConfig()\">\n"
        "        </div>\n"
        "\n"
        "        <div class=\"form-group\" id=\"php-group\" style=\"display: none;\">\n"
        "            <label for=\"phpver\">PHP Socket / Version</label>\n"
        "            <input type=\"text\" id=\"phpver\" value=\"auto\" placeholder=\"auto or e.g. 8.2\" oninput=\"generateConfig()\">\n"
        "        </div>\n"
        "    </div>\n"
        "\n"
        "    <!-- Output Panel -->\n"
        "    <div class=\"card\">\n"
        "        <h2>Generated NGINX Config</h2>\n"
        "        <pre id=\"output\"></pre>\n"
        "        <button class=\"btn-apply\" onclick=\"applyConfig()\">Apply Configuration</button>\n"
        "    </div>\n"
        "</div>\n"
        "\n"
        "<script>\n"
        "function toggleFields() {\n"
        "    const preset = document.getElementById('preset').value;\n"
        "    const portGroup = document.getElementById('port-group');\n"
        "    const pathGroup = document.getElementById('path-group');\n"
        "    const phpGroup = document.getElementById('php-group');\n"
        "    const nameInput = document.getElementById('conf_name');\n"
        "\n"
        "    portGroup.style.display = 'none';\n"
        "    pathGroup.style.display = 'none';\n"
        "    phpGroup.style.display = 'none';\n"
        "\n"
        "    if (preset === 'jellyfin') {\n"
        "        portGroup.style.display = 'block';\n"
        "        document.getElementById('port').value = '8096';\n"
        "        nameInput.value = 'jellyfin';\n"
        "    } else if (preset === 'nextcloud') {\n"
        "        phpGroup.style.display = 'block';\n"
        "        pathGroup.style.display = 'block';\n"
        "        document.getElementById('path').value = '/var/www/nextcloud';\n"
        "        nameInput.value = 'nextcloud';\n"
        "    } else if (preset === 'custom_proxy') {\n"
        "        portGroup.style.display = 'block';\n"
        "        nameInput.value = 'custom-proxy';\n"
        "    } else if (preset === 'custom_static') {\n"
        "        pathGroup.style.display = 'block';\n"
        "        nameInput.value = 'custom-static';\n"
        "    }\n"
        "\n"
        "    generateConfig();\n"
        "}\n"
        "\n"
        "function generateConfig() {\n"
        "    const preset = document.getElementById('preset').value;\n"
        "    const domain = document.getElementById('domain').value || 'example.com';\n"
        "    const port = document.getElementById('port').value || '8080';\n"
        "    const path = document.getElementById('path').value || '/var/www/html';\n"
        "    let phpver = document.getElementById('phpver').value || 'auto';\n"
        "    \n"
        "    if (phpver === 'auto') {\n"
        "        phpver = '8.2';\n"
        "    }\n"
        "\n"
        "    let config = '';\n"
        "\n"
        "    if (preset === 'jellyfin') {\n"
        "        config = `server {\n"
        "    server_name ${domain};\n"
        "\n"
        "    location / {\n"
        "        proxy_pass http://127.0.0.1:${port};\n"
        "        proxy_set_header Host $host;\n"
        "        proxy_set_header X-Real-IP $remote_addr;\n"
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "        proxy_set_header X-Forwarded-Proto $scheme;\n"
        "        proxy_set_header X-Forwarded-Protocol $scheme;\n"
        "        proxy_set_header X-Forwarded-Host $http_host;\n"
        "        \n"
        "        # WebSockets support\n"
        "        proxy_http_version 1.1;\n"
        "        proxy_set_header Upgrade $http_upgrade;\n"
        "        proxy_set_header Connection \"upgrade\";\n"
        "    }\n"
        "}`;\n"
        "    } else if (preset === 'nextcloud') {\n"
        "        config = `upstream php-handler {\n"
        "    server unix:/run/php/php${phpver}-fpm.sock;\n"
        "}\n"
        "\n"
        "server {\n"
        "    listen 80;\n"
        "    server_name ${domain};\n"
        "    return 301 https://$server_name$request_uri;\n"
        "}\n"
        "\n"
        "server {\n"
        "    listen 443 ssl http2;\n"
        "    server_name ${domain};\n"
        "    root ${path};\n"
        "\n"
        "    client_max_body_size 512M;\n"
        "    client_body_timeout 300s;\n"
        "\n"
        "    location / {\n"
        "        try_files $uri $uri/ /index.php$request_uri;\n"
        "    }\n"
        "\n"
        "    location ~ \\\\.php$ {\n"
        "        include fastcgi_params;\n"
        "        fastcgi_pass php-handler;\n"
        "        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\n"
        "    }\n"
        "}`;\n"
        "    } else if (preset === 'custom_proxy') {\n"
        "        config = `server {\n"
        "    server_name ${domain};\n"
        "\n"
        "    location / {\n"
        "        proxy_pass http://127.0.0.1:${port};\n"
        "        proxy_set_header Host $host;\n"
        "        proxy_set_header X-Real-IP $remote_addr;\n"
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "        proxy_set_header X-Forwarded-Proto $scheme;\n"
        "    }\n"
        "}`;\n"
        "    } else if (preset === 'custom_static') {\n"
        "        config = `server {\n"
        "    server_name ${domain};\n"
        "    root ${path};\n"
        "    index index.html index.htm;\n"
        "\n"
        "    location / {\n"
        "        try_files $uri $uri/ =404;\n"
        "    }\n"
        "}`;\n"
        "    }\n"
        "\n"
        "    document.getElementById('output').textContent = config;\n"
        "}\n"
        "\n"
        "async function applyConfig() {\n"
        "    const payload = {\n"
        "        preset: document.getElementById('preset').value,\n"
        "        name: document.getElementById('conf_name').value,\n"
        "        domain: document.getElementById('domain').value,\n"
        "        port: document.getElementById('port').value,\n"
        "        path: document.getElementById('path').value,\n"
        "        phpver: document.getElementById('phpver').value\n"
        "    };\n"
        "\n"
        "    try {\n"
        "        const response = await fetch('api.php', {\n"
        "            method: 'POST',\n"
        "            headers: { 'Content-Type': 'application/json' },\n"
        "            body: JSON.stringify(payload)\n"
        "        });\n"
        "\n"
        "        const result = await response.json();\n"
        "        alert(result.message || result.error);\n"
        "    } catch (err) {\n"
        "        alert('Failed to connect to backend: ' + err.message);\n"
        "    }\n"
        "}\n"
        "\n"
        "generateConfig();\n"
        "</script>\n"
        "\n"
        "</body>\n"
        "</html>\n"
  );

  fclose(ht);

  char php_code[STR_LEN];
  snprintf(php_code, sizeof(php_code), "/var/www/auto-config/api.php");
  FILE *ph = fopen(php_code, "w");
  fprintf(ph,
  "<?php\n"
        "header('Content-Type: application/json');\n"
        "\n"
        "// Read raw JSON body from fetch request\n"
        "$json_data = file_get_contents('php://input');\n"
        "$data = json_decode($json_data, true);\n"
        "\n"
        "if (!$data || empty($data['name'])) {\n"
        "    echo json_encode(['error' => 'Invalid configuration data provided.']);\n"
        "    exit;\n"
        "}\n"
        "\n"
        "// Write the parameters to a temporary JSON file\n"
        "$json_file = '/tmp/nginx_config_input.json';\n"
        "file_put_contents($json_file, json_encode($data, JSON_PRETTY_PRINT));\n"
        "\n"
        "// Execute the C binary passing the JSON file path\n"
        "$cmd = \"sudo /usr/local/bin/nginx-auto --json \" . escapeshellarg($json_file) . \" 2>&1\";\n"
        "exec($cmd, $output, $return_var);\n"
        "\n"
        "if ($return_var === 0) {\n"
        "    echo json_encode([\n"
        "        'status' => 'success',\n"
        "        'message' => 'Configuration generated and applied successfully!'\n"
        "    ]);\n"
        "} else {\n"
        "    echo json_encode([\n"
        "        'status' => 'error',\n"
        "        'error' => implode(\"\\n\", $output)\n"
        "    ]);\n"
        "}\n"
        "?>\n"
  );

  fclose(ph);

  //test these
  system("echo 'www-data ALL=(ALL) NOPASSWD: /usr/local/bin/nginx-auto' | sudo tee /etc/sudoers.d/nginx-auto > /dev/null");
  system("chmod 0440 /etc/sudoers.d/nginx-auto");

  system("sudo systemctl reload nginx");

  find_ip();
  printf("Visit \033[34mhttp://%s:3487\033[0m to use the GUI\n\n", lan_ip);

  return;
}